### ISSUE TITLE
Teams: Should not be able to assign a camper to a team when still in shopping cart

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#110]
Self explanatory

**Comment by timeforcamp** [comment]
Why not? There is not harm in doing this? The camper doesn't show up in the team view until they are paid in full.

**Comment by DENICHOLS** [comment]
Because I can see him assigned to the Team as a Camp or Organization Admin, I can sort campers by Team and see him in there, but then when I go to print profiles or the roster he is not on the team.  So it is pointless to do and may just end up causing confusion.  "I seem him assigned to the team right here, but why is he not on the roster or on a camper profile?"

![image](https://user-images.githubusercontent.com/13508954/74591904-cfc12900-4fe1-11ea-9102-72ef31b48149.png)

![image](https://user-images.githubusercontent.com/13508954/74591900-a7392f00-4fe1-11ea-9799-0a9ce41b4225.png)

**Comment by timeforcamp** [comment]
Once again that is by design, he isn't on the roster because the registration is not paid in full. However, as a camp admin, you are planning out your teams it makes sense to have the ability to add them to teams (same is true for deposits). The camper has not paid so therefore he doesn't show on the roster.

**Comment by DENICHOLS** [comment]
The ability to assign the attendee to a team while still in a pending (in shopping cart / balance due) state allows for the event admin to plan ahead.
