### ISSUE TITLE
Product Delivery for Inactive Registration

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#117]
Have a registration that included a store item.  Registration was refunded, but the store item was not refunded.

How would the camp admin go about marking the product as delivered should they still show up to camp to retrieve it?  This will be an issue since we don't force the refund of store items when the associated registration is refunded.

1) When inactive, there is no check-in option
![image](https://user-images.githubusercontent.com/13508954/74590924-bf588080-4fd8-11ea-8463-088f149eda6d.png)

2) When you toggle them back to active, the status is REFUNDED-NOT CHECKED IN, but there is no CHECK-IN option
![image](https://user-images.githubusercontent.com/13508954/74590931-d1d2ba00-4fd8-11ea-85a0-bb90dec8a383.png)

**Comment by timeforcamp** [comment]
"This will be an issue since we don't force the refund of store items when the associated registration is refunded." this is entirely up the camp administrator. They could be refunding the registration for any number of reasons but still handing out the store item that was purchased. 

The second part of this is a bug re: Check-In should be there even though the registration was refunded. Would recommend not combining issues so that we can easily track things.
