### ISSUE TITLE
Vendor product fields - remove items meant for event admin completion

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#188]
**As I am writing this, I realize that we may HAVE to give them this information due to required elements on the page.**

Vendor rep should not be able to set the event cost for the event...only their cost.

Also, probably does not need to see the visibility information or make those changes for the three visibility settings.

![image](https://user-images.githubusercontent.com/13508954/94089002-8e92c200-fdd7-11ea-89da-0384faa953cc.png)

**Comment by timeforcamp** [comment]
This is by design, the control of the product for the event is really up to the event admin. If they want to override any of this information they have the ability to do so. However, if the vendor is being asked, and is willing, to do more it is easier for us to just allow it here and give the event admin the ability to change it.
